version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
#    networks:
#      - db_net



  tg_bot:
    #image: ovcserega/twittertgbot
    build: .
    ports:
      - "8080:8080"
#    networks:
#      - db_net
    environment:
      TOKEN: 1181332527:AAFukyDAcmpzfaRSrasU1Yf_t7i6gOs59TU
    depends_on:
      - db

networks:
  db_net: