# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/114/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/114/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kiayria/myProjects/Twitter-API-C-Library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kiayria/myProjects/Twitter-API-C-Library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/snap/clion/114/bin/cmake/linux/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kiayria/myProjects/Twitter-API-C-Library/CMakeFiles /home/kiayria/myProjects/Twitter-API-C-Library/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kiayria/myProjects/Twitter-API-C-Library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compile_commands

# Build rule for target.
compile_commands: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compile_commands
.PHONY : compile_commands

# fast build rule for target.
compile_commands/fast:
	$(MAKE) -f CMakeFiles/compile_commands.dir/build.make CMakeFiles/compile_commands.dir/build
.PHONY : compile_commands/fast

#=============================================================================
# Target rules for targets named networklib

# Build rule for target.
networklib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 networklib
.PHONY : networklib

# fast build rule for target.
networklib/fast:
	$(MAKE) -f networklib/CMakeFiles/networklib.dir/build.make networklib/CMakeFiles/networklib.dir/build
.PHONY : networklib/fast

#=============================================================================
# Target rules for targets named twitterlib

# Build rule for target.
twitterlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twitterlib
.PHONY : twitterlib

# fast build rule for target.
twitterlib/fast:
	$(MAKE) -f twitterlib/CMakeFiles/twitterlib.dir/build.make twitterlib/CMakeFiles/twitterlib.dir/build
.PHONY : twitterlib/fast

#=============================================================================
# Target rules for targets named demos

# Build rule for target.
demos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demos
.PHONY : demos

# fast build rule for target.
demos/fast:
	$(MAKE) -f demos/CMakeFiles/demos.dir/build.make demos/CMakeFiles/demos.dir/build
.PHONY : demos/fast

#=============================================================================
# Target rules for targets named search

# Build rule for target.
search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 search
.PHONY : search

# fast build rule for target.
search/fast:
	$(MAKE) -f demos/CMakeFiles/search.dir/build.make demos/CMakeFiles/search.dir/build
.PHONY : search/fast

#=============================================================================
# Target rules for targets named get_favorites

# Build rule for target.
get_favorites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_favorites
.PHONY : get_favorites

# fast build rule for target.
get_favorites/fast:
	$(MAKE) -f demos/CMakeFiles/get_favorites.dir/build.make demos/CMakeFiles/get_favorites.dir/build
.PHONY : get_favorites/fast

#=============================================================================
# Target rules for targets named readme

# Build rule for target.
readme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readme
.PHONY : readme

# fast build rule for target.
readme/fast:
	$(MAKE) -f demos/CMakeFiles/readme.dir/build.make demos/CMakeFiles/readme.dir/build
.PHONY : readme/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named blocks

# Build rule for target.
blocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blocks
.PHONY : blocks

# fast build rule for target.
blocks/fast:
	$(MAKE) -f tests/rest/CMakeFiles/blocks.dir/build.make tests/rest/CMakeFiles/blocks.dir/build
.PHONY : blocks/fast

#=============================================================================
# Target rules for targets named favorites

# Build rule for target.
favorites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 favorites
.PHONY : favorites

# fast build rule for target.
favorites/fast:
	$(MAKE) -f tests/rest/CMakeFiles/favorites.dir/build.make tests/rest/CMakeFiles/favorites.dir/build
.PHONY : favorites/fast

#=============================================================================
# Target rules for targets named statuses

# Build rule for target.
statuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 statuses
.PHONY : statuses

# fast build rule for target.
statuses/fast:
	$(MAKE) -f tests/rest/CMakeFiles/statuses.dir/build.make tests/rest/CMakeFiles/statuses.dir/build
.PHONY : statuses/fast

#=============================================================================
# Target rules for targets named collections

# Build rule for target.
collections: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collections
.PHONY : collections

# fast build rule for target.
collections/fast:
	$(MAKE) -f tests/rest/CMakeFiles/collections.dir/build.make tests/rest/CMakeFiles/collections.dir/build
.PHONY : collections/fast

#=============================================================================
# Target rules for targets named account

# Build rule for target.
account: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 account
.PHONY : account

# fast build rule for target.
account/fast:
	$(MAKE) -f tests/rest/CMakeFiles/account.dir/build.make tests/rest/CMakeFiles/account.dir/build
.PHONY : account/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) -f tests/rest/CMakeFiles/application.dir/build.make tests/rest/CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named rest_tests

# Build rule for target.
rest_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rest_tests
.PHONY : rest_tests

# fast build rule for target.
rest_tests/fast:
	$(MAKE) -f tests/rest/CMakeFiles/rest_tests.dir/build.make tests/rest/CMakeFiles/rest_tests.dir/build
.PHONY : rest_tests/fast

#=============================================================================
# Target rules for targets named stream_tests

# Build rule for target.
stream_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_tests
.PHONY : stream_tests

# fast build rule for target.
stream_tests/fast:
	$(MAKE) -f tests/streams/CMakeFiles/stream_tests.dir/build.make tests/streams/CMakeFiles/stream_tests.dir/build
.PHONY : stream_tests/fast

#=============================================================================
# Target rules for targets named sample_stream

# Build rule for target.
sample_stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_stream
.PHONY : sample_stream

# fast build rule for target.
sample_stream/fast:
	$(MAKE) -f tests/streams/CMakeFiles/sample_stream.dir/build.make tests/streams/CMakeFiles/sample_stream.dir/build
.PHONY : sample_stream/fast

#=============================================================================
# Target rules for targets named user_stream

# Build rule for target.
user_stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 user_stream
.PHONY : user_stream

# fast build rule for target.
user_stream/fast:
	$(MAKE) -f tests/streams/CMakeFiles/user_stream.dir/build.make tests/streams/CMakeFiles/user_stream.dir/build
.PHONY : user_stream/fast

#=============================================================================
# Target rules for targets named filtered_stream

# Build rule for target.
filtered_stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filtered_stream
.PHONY : filtered_stream

# fast build rule for target.
filtered_stream/fast:
	$(MAKE) -f tests/streams/CMakeFiles/filtered_stream.dir/build.make tests/streams/CMakeFiles/filtered_stream.dir/build
.PHONY : filtered_stream/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... compile_commands"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... networklib"
	@echo "... twitterlib"
	@echo "... demos"
	@echo "... search"
	@echo "... get_favorites"
	@echo "... readme"
	@echo "... tests"
	@echo "... blocks"
	@echo "... favorites"
	@echo "... statuses"
	@echo "... collections"
	@echo "... account"
	@echo "... application"
	@echo "... rest_tests"
	@echo "... stream_tests"
	@echo "... sample_stream"
	@echo "... user_stream"
	@echo "... filtered_stream"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

